services:

  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: [/app]
    env_file:
      - .env
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=cats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "cats" ]
      interval: 1s
      timeout: 5s
      retries: 10

  flyway:
    image: flyway/flyway:latest
    command:
      -url=jdbc:postgresql://postgres:5432/cats -user=user -password=password -validateMigrationNaming="true" -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

  
